In [1]:
#numpy(전처리), pandas(분석) 병행
#matplotlib, seaborn 시각화
"""
전처리:결측치, 표준화/정규화
정규화:각 국어점수-최소/국어점수의 최대-최소
=>0~1
표준화:평균-0, 표준편차-1
각 국어점수-평균 / 국어점수 표준편차
원핫인코딩:100000, 010000, 001000,...
             A       B       C     D   E  F
문장 추출 -> 단어(5개) 추출 -> 원핫인코딩
국어10000
영어01000
수학00100
과학00010
윤리00001

문장 추출 -> 단어(5개) 추출 -> 밀집벡터(워드2벡터)
국어 [0.2, 0.7]
수학 [0.1, 0.3]
...
             
             
"""

'\n전처리:결측치, 표준화/정규화\n정규화:각 국어점수-최소/국어점수의 최대-최소\n=>0~1\n표준화:평균-0, 표준편차-1\n각 국어점수-평균 / 국어점수 표준편차\n원핫인코딩:100000, 010000, 001000,...\n             A       B       C     D   E  F\n문장 추출 -> 단어(5개) 추출 -> 원핫인코딩\n국어10000\n영어01000\n수학00100\n과학00010\n윤리00001\n\n문장 추출 -> 단어(5개) 추출 -> 밀집벡터(워드2벡터)\n국어 [0.2, 0.7]\n수학 [0.1, 0.3]\n...\n             \n             \n'

In [2]:
"""
1. 
리스트:속도느림, 메모리 많이 차지
배열(array):속도빠름, 메모리 적게 차지

2.
넘파이 배열과 리스트의 차이점
-배열은 모두 같은 자료형,원소 개수 변경 못함
-배열은 파이썬에서 제공하지 않음
-파이썬 환경에서 넘파이 패키지를 활용하여
배열을 사용할 수 있음

3. 넘파이? 수치해석 패키지, 다차원 배열 구조
벡터, 행렬을 사용하는 선행대수 계산시 사용
넘파이 배열 연산 빠름(벡터화 연산)

"""

'\n1. \n리스트:속도느림, 메모리 많이 차지\n배열(array):속도빠름, 메모리 적게 차지\n\n2.\n넘파이 배열과 리스트의 차이점\n-배열은 모두 같은 자료형,원소 개수 변경 못함\n-배열은 파이썬에서 제공하지 않음\n-파이썬 환경에서 넘파이 패키지를 활용하여\n배열을 사용할 수 있음\n\n3. 넘파이? 수치해석 패키지, 다차원 배열 구조\n벡터, 행렬을 사용하는 선행대수 계산시 사용\n넘파이 배열 연산 빠름(벡터화 연산)\n\n'

In [3]:
#1차원 배열
import numpy
ar=numpy.array([0,1,2,3,4])
ar
type(ar)

numpy.ndarray

In [4]:
# 100*100 크기의 이미지(픽셀:10000 개)
# 0~255사이의 gray scale
# => 몇 차원?

In [9]:
data=list(range(1,101))
#data에 저장된 모든 값들에 대해 2배
# sum=0
# d=100
# print(d*(d+1)/2)   #O(1)

# for d in data:
#     sum+=d  #  O(n)
# print(sum)

#시간복잡도(CPU)
#연산 결과가 나오기까지 수행되는 라인의 수
#공간 복잡도(MEMORY)


5050.0


In [12]:
ans=[]
data=list(range(1,11))
for d in data:
    ans.append(d*2)
print(ans)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


In [3]:
import numpy as np
# x=np.array(data)
# x*2 #벡터화 연산:
# #data*2

In [6]:
a=np.array([1,2,3])
#          [2,2,2]  요소간 연산:element wise ~
b=np.array([4,5,6])
a2=[1,2,3]
b2=[4,5,6]

In [10]:
2*a2+b2 #[1, 2, 3, 1, 2, 3, 4, 5, 6]
2*a+b #벡터화 연산

array([ 6,  9, 12])

In [16]:
#a
a2==2
a==2 #논리연산

a>2#비교연산

array([False, False,  True])

In [17]:
#2차원 배열(행렬, matrix)
#가로줄:행, 세로줄:열

In [28]:
#2차원배열:리스트의 리스트
m=np.array([[0,1,2],[3,4,5]])
m
#열 : 안쪽 리스트 길이, 가로 크기
#행 : 바깥쪽 리스트 길이, 세로 크기
#2행 3열
# 0 1 2 
# 3 4 5
len(m)  #행의 개수
len(m[0]) #열의 개수

3

In [38]:
#3차원 배열:리스트의 리스트의 리스트
m=np.array([[[1,2,3,4],
          [5,6,7,8],
          [9,10,11,12]],
        [[31,2,3,4],
          [35,6,7,8],
          [39,10,11,12]]])
#2행 3열 4깊이(면)
#2*3*4
len(m)
len(m[0])
len(m[0][0])

print(m.ndim)
print(m.shape)


3
(2, 3, 4)


In [33]:
a=np.array([4,5,6])
a.ndim #배열의 차원
a.shape #배열의 크기

(3,)

In [36]:
m=np.array([[0,1,2],[3,4,5]])
m.ndim

m.shape #2행 3열

(2, 3)

In [39]:
#1.
# [3,2,1,-4,-,7, -9, 8, -5, 3, -1]
# 연속으로 숫자 3개를 곱했을때 얻어진 결과값이
# 가장 큰 구간이 어디인지 출력
# #2.
# #2*2의 영역을 구성하는 수를 곱했을때 얻어진 
# # 결과값이 가장 큰 구간이 어디인지 출력
# [[3, 1, -2],
#  [2, 1, -3],
#  [-2,0, -7]]

In [48]:
#array slicing
ar=np.array([[1,2,3,4], [5,6,7,8]])
ar
ar[0]
ar[0,:]#첫번째 행 전체
ar[:,1]#두번째 열 전체

ar[1,1:]#두번째 행에서 두번째 열부터 마지막까지

ar[:,0:2]
ar[:,:2]
ar[:2,:2]

array([[1, 2],
       [5, 6]])

In [64]:
#indexing:데이터 1개를 참조
ar=np.array([0,1,2])
ar[1]
ar[-1]

ar=np.array([[1,2,3,4], [5,6,7,8]])
ar[0][0]
ar[0,0]#다차원 배열에서는 컴마로 접근
ar[0,1]#2

#6을 추출, 두번째 행의 두번째 열
ar[1][1] 
ar[1,1]
ar[-1][1]
ar[-1,1]
ar[-1,-3]
ar[-1][-3]

6

In [73]:
#불린 참조:조건에 대해 만족하는 값을 추출
ar=np.array([2,3,4,5])
bidx=np.array([True, True, False, True])
ar[bidx]
ar[ar != 4]
#ar 요소값이 짝수인 것들만 추출
ar[ar % 2 == 0]

#ar 요소값이 3보다 큰 값들만 추출
ar[ar > 3]





array([4, 5])

In [75]:
#정수 참조 추출
ar=np.array([2,3,4,5])
idx=np.array([0,3])
ar[idx]

idx=np.array([0,0,1,1])
ar[idx]

array([2, 2, 3, 3])

In [79]:
ar=np.array([[1,2,3,4], [5,6,7,8]])
ar[:,[0,3]]
#[[1,4],
# [5,8]]
ar[:,[True,False, False, True]]

array([[1, 4],
       [5, 8]])

In [90]:
ar=np.array([[1,2,3,4], 
             [15,16,17,18],
             [25,26,27,28],
             [35,36,37,38]])
ar[[2,0,-1],:]
# ar[:] #ar 전체 행
# ar #ar 배열 전체
# ar[:,:] #전체 행 전체 열

array([[25, 26, 27, 28],
       [ 1,  2,  3,  4],
       [35, 36, 37, 38]])

In [ ]:
#원데이터 : csv, tsv, txt, xls, xlsx, json, xml...
#Pandas : 원데이터를 데이터프레임(엑셀 시트)으로 읽어서 분석
#Numpy : 원데이터를 다차원배열으로 읽어서 처리

In [92]:
import pandas as pd
csvTest=pd.read_csv("test_csv.csv")
#csvTest
type(csvTest)

pandas.core.frame.DataFrame

In [96]:
#http://pandas.pydata.org/
csvTest.shape[1]   #    (5, 3)  : 튜플


3

In [103]:
# test_text.txt
# 구분자 : |
text=pd.read_csv("test_text.txt", sep="|")
text
#text.shape # (5,1)

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30