In [1]:
"""
정규화:0~1사이의 범위로 데이터를 표준화

5 3 1 7 9 => 0~1 =>  각데이터값-최소값 / 최대값-최소값
5-1 / 9-1 => 0.5
3-1 / 9-1 => ...
1-1 / 9-1 => 0
...
9-1 / 9-1 => 1

"""

'\n정규화:0~1사이의 범위로 데이터를 표준화\n\n5 3 1 7 9 => 0~1 =>  각데이터값-최소값 / 최대값-최소값\n5-1 / 9-1 => 0.5\n3-1 / 9-1 => ...\n1-1 / 9-1 => 0\n...\n9-1 / 9-1 => 1\n\n'

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [4]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [11]:
data_mm=(data-data.min(axis=0))/ (data.max(axis=0)-data.min(axis=0))
# data.max() #data 배열 전체에서 최대값
# data.max(axis=0) #각 열 단위 최대값
# data.max(axis=1) #각 행 단위 최대값

In [13]:
mms=MinMaxScaler()
datamms=mms.fit_transform(data)
datamms

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [14]:
from sklearn.preprocessing import minmax_scale

In [15]:
datamm=minmax_scale(data,axis=0)
datamm

array([[1.        , 0.        , 0.        ],
       [0.5       , 0.58823529, 1.        ],
       [0.        , 1.        , 0.5       ]])

In [16]:
#이항변수화:연속형변수를 기준이하->0, 기준초과->1
#확률변수 X가 이항분포를 따른다고 했을때, 
#0또는 1값을 갖는 이항변수화가 필요
#베르누이시행:성공(1),실패(0) 두가지 경우만 존재
#성공확률이 p인 베르누이시행을 n번 수행.
#성공하는 횟수를 x라고하면,
#확률변수 x는 모수 n과 p인 이항분포를 따른다

"""
주사위 : 3
3이 나올 확률(성공) : 1/6
실패:1/6

A, B, C, D
(A만 성공, B만 성공, C만 성공, D만 성공)
A만성공:1/6*5/6*5/6*5/6=0.09
B만성공:1/6*5/6*5/6*5/6=0.09
C만성공:1/6*5/6*5/6*5/6=0.09
D만성공:1/6*5/6*5/6*5/6=0.09
0.09*4 = 0.36
성공확률(p)*시나리오수(n)
"""




'\n주사위 : 3\n3이 나올 확률(성공) : 1/6\n실패:1/6\n\nA, B, C, D\n(A만 성공, B만 성공, C만 성공, D만 성공)\nA만성공:1/6*5/6*5/6*5/6=0.09\nB만성공:1/6*5/6*5/6*5/6=0.09\nC만성공:1/6*5/6*5/6*5/6=0.09\nD만성공:1/6*5/6*5/6*5/6=0.09\n0.09*4 = 0.36\n성공확률(p)*시나리오수(n)\n'

In [17]:
from sklearn.preprocessing import Binarizer

In [18]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [27]:
bina=Binarizer(5).fit(data) #5이하(0), 5초과(1)
bina

Binarizer(copy=True, threshold=5)

In [28]:
bina.transform(data)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [31]:
from sklearn.preprocessing import binarize

In [32]:
data=np.array([[10,-10,2],
              [5,0,6],
              [0,7,4]])
data

array([[ 10, -10,   2],
       [  5,   0,   6],
       [  0,   7,   4]])

In [37]:
binarize(data, threshold=5,copy=False) #copy=True default
#copy=False이면, 원본 데이터로 binarize하기때문에 원본 변화


array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [38]:
data

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 0]])

In [39]:
#바이너라이저 : 연속형 변수를 이항변수화
#원핫인코더 : 범주형 변수를 이항변수화
"""
연령대:20대->0, 30대->1, 40대->2
성별:남->0, 여->1
학점: A:0,B:1,C:2,D:3,F:4

20대 여 B => 100 01 01000
30대 남 D -> 010 10 00010

학점
01234
10000(A)
01000(B)
...
00001(F)

"""

'\n연령대:20대->0, 30대->1, 40대->2\n성별:남->0, 여->1\n학점: A:0,B:1,C:2,D:3,F:4\n\n20대 여 B => 100 01 01000\n30대 남 D -> 010 10 00010\n\n학점\n01234\n10000(A)\n01000(B)\n...\n00001(F)\n\n'

In [40]:
from sklearn.preprocessing import OneHotEncoder

In [42]:
#           [성별,연령,학점]
data=np.array([[0,0,0],
               [0,1,1],
               [0,2,2],
               [1,0,3],
               [1,1,4]
              ])
data

array([[0, 0, 0],
       [0, 1, 1],
       [0, 2, 2],
       [1, 0, 3],
       [1, 1, 4]])

In [43]:
ohe=OneHotEncoder()
ohe.fit(data)

C:\Users\student\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None, drop=None,
              dtype=<class 'numpy.float64'>, handle_unknown='error',
              n_values=None, sparse=True)

In [49]:
ohe.active_features_
#[남,여,20,30,40,a,b,c,d,f]

ohe.n_values_
#범주 개수

ohe.feature_indices_
#성별:0이상 2미만, 
#연령:2이상 5미만, 
#학점:5이상 10미만

array([ 0,  2,  5, 10], dtype=int32)

In [51]:
#범주형 데이터 -> 이항변수화
data=np.array([[1,2,3]]) #여성 40대 D학점
ohe.transform(data).toarray()

array([[0., 1., 0., 0., 1., 0., 0., 0., 1., 0.]])

In [53]:
df = pd.DataFrame({'C1': np.random.randn(20),
   'C2': ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a',
   'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b', 'b']})
df

C1 C2
0   0.322085  a
1  -0.522438  a
2  -0.350268  a
3  -1.732098  a
4   0.148904  a
5  -0.388351  a
6   1.220266  a
7   0.023982  a
8  -0.479574  a
9  -1.287902  a
10  0.181119  b
11 -0.110423  b
12  0.399319  b
13  1.370442  b
14 -0.859877  b
15 -0.317889  b
16 -0.633059  b
17 -0.428216  b
18  0.141081  b
19  0.884973  b

In [55]:
"""
np.digitize함수, np.where함수: 연속형 변수 -> 이산화
이항변수화: 0또는 1 값을 갖는 변수를 만드는 것
이산(형)화:연속형 변수를 2개 이상의 범주를 
갖는 변수로 변환
ex)점수:75->A/B/C/D/F(범주=category)
"""
np.random.seed(10)#42, 777, 1004
np.random.randn(1)

array([1.3315865])

In [64]:
"""
df의 c1열 20개 data구성
10개 bin으로 균등하게 나눔
"""
df.C1.min() #-1.732
df.C1.max() # 1.370
bins=np.linspace(df.C1.min(), df.C1.max(), 10)
bins
df.C1
df['C1_bin']=np.digitize(df['C1'], bins)
df

C1 C2  C1_bin
0   0.322085  a       6
1  -0.522438  a       4
2  -0.350268  a       5
3  -1.732098  a       1
4   0.148904  a       6
5  -0.388351  a       4
6   1.220266  a       9
7   0.023982  a       6
8  -0.479574  a       4
9  -1.287902  a       2
10  0.181119  b       6
11 -0.110423  b       5
12  0.399319  b       7
13  1.370442  b      10
14 -0.859877  b       3
15 -0.317889  b       5
16 -0.633059  b       4
17 -0.428216  b       4
18  0.141081  b       6
19  0.884973  b       8

In [72]:
#구간별로 요약통계, 범주간 평균 차이
#독립성검정, indexing...
df.groupby('C1_bin')['C1'].size()
df.groupby('C1_bin')['C1'].mean()
df.groupby('C1_bin')['C1'].std()
df.groupby('C1_bin')['C2'].value_counts()

df[df['C1_bin']==4]

C1 C2  C1_bin
1  -0.522438  a       4
5  -0.388351  a       4
8  -0.479574  a       4
16 -0.633059  b       4
17 -0.428216  b       4

In [75]:
#pd.get_dummies():가변수 생성
pd.get_dummies(df['C1_bin'], prefix='C1')

#모델=x1*가중치+x2*가중치+...+x10*가중치+바이어스


C1_1  C1_2  C1_3  C1_4  C1_5  C1_6  C1_7  C1_8  C1_9  C1_10
0      0     0     0     0     0     1     0     0     0      0
1      0     0     0     1     0     0     0     0     0      0
2      0     0     0     0     1     0     0     0     0      0
3      1     0     0     0     0     0     0     0     0      0
4      0     0     0     0     0     1     0     0     0      0
5      0     0     0     1     0     0     0     0     0      0
6      0     0     0     0     0     0     0     0     1      0
7      0     0     0     0     0     1     0     0     0      0
8      0     0     0     1     0     0     0     0     0      0
9      0     1     0     0     0     0     0     0     0      0
10     0     0     0     0     0     1     0     0     0      0
11     0     0     0     0     1     0     0     0     0      0
12     0     0     0     0     0     0     1     0     0      0
13     0     0     0     0     0     0     0     0     0      1
14     0     0     1     0     0     0     0     0     0      0
15     0     0     0     0     1     0     0     0     0      0
16     0     0     0     1     0     0     0     0     0      0
17     0     0     0     1     0     0     0     0     0      0
18     0     0     0     0     0     1     0     0     0      0
19     0     0     0     0     0     0     0     1     0      0

In [80]:
#np.where(조건, 참, 거짓)
df['h_l']=np.where(df['C1']>=df.C1.mean(),
                   "high","low")
df
df.groupby('h_l')['C1'].size()
df.groupby('h_l')['C1'].mean()
df.groupby('h_l')['C1'].std()

h_l
high    0.516606
low     0.466705
Name: C1, dtype: float64

In [83]:
Q1=np.percentile(df['C1'],25)
Q3=np.percentile(df['C1'],75)
#연습문제: C1열 값 <= Q1 then df['h_m_l']=l
#C1열 값 > Q1 and <=Q3 then df['h_m_l']=m
#else then df['h_m_l']=h
df['h_m_l']=np.where(df['C1']>=Q3,'high',
                     np.where(df['C1']>=Q1,
                              'medium','low'))


In [84]:
df

C1 C2  C1_bin   h_l   h_m_l
0   0.322085  a       6  high    high
1  -0.522438  a       4   low     low
2  -0.350268  a       5   low  medium
3  -1.732098  a       1   low     low
4   0.148904  a       6  high  medium
5  -0.388351  a       4   low  medium
6   1.220266  a       9  high    high
7   0.023982  a       6  high  medium
8  -0.479574  a       4   low  medium
9  -1.287902  a       2   low     low
10  0.181119  b       6  high  medium
11 -0.110423  b       5  high  medium
12  0.399319  b       7  high    high
13  1.370442  b      10  high    high
14 -0.859877  b       3   low     low
15 -0.317889  b       5   low  medium
16 -0.633059  b       4   low     low
17 -0.428216  b       4   low  medium
18  0.141081  b       6  high  medium
19  0.884973  b       8  high    high

In [85]:
"""
데이터 재구조화
-피봇테이블(pivot, pivot_table)
-스택(stack, unstack)
-멜트(melt)
-wide_to_long, crosstab
"""

'\n데이터 재구조화\n'

In [88]:
data = pd.DataFrame({
    'cust_id': ['c1', 'c1', 'c1', 'c2', 'c2', 'c2', 'c3', 'c3', 'c3'],
    'prod_cd': ['p1', 'p2', 'p3', 'p1', 'p2', 'p3', 'p1', 'p2', 'p3'],
    'grade' : ['A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B'],
    'pch_amt': [30, 10, 0, 40, 15, 30, 0, 0, 10]})
data

cust_id prod_cd grade  pch_amt
0      c1      p1     A       30
1      c1      p2     A       10
2      c1      p3     A        0
3      c2      p1     A       40
4      c2      p2     A       15
5      c2      p3     A       30
6      c3      p1     B        0
7      c3      p2     B        0
8      c3      p3     B       10

In [94]:
#       p1 p2 p3
# cid
# c1   30 10   0  
# c2   40 15  30
# c3    ...

#data.pivot(index='cust_id',columns='prod_cd',values='pch_amt')
pd.pivot_table(data,index='cust_id',columns='prod_cd',values='pch_amt')

# data.pivot(index=['cust_id', 'grade'],
#            columns='prod_cd',
#            values='pch_amt')
#에러

pd.pivot_table(data,index=['cust_id', 'grade'],
               columns='prod_cd',
               values='pch_amt')

pd.pivot_table(data,index='cust_id',
               columns=['grade','prod_cd'],
               values='pch_amt')

grade       A                B           
prod_cd    p1    p2    p3   p1   p2    p3
cust_id                                  
c1       30.0  10.0   0.0  NaN  NaN   NaN
c2       40.0  15.0  30.0  NaN  NaN   NaN
c3        NaN   NaN   NaN  0.0  0.0  10.0

In [100]:
#pivot_table: 집계함수 제공
pd.pivot_table(data, index="grade", columns='prod_cd', values='pch_amt')
#default: 평균
pd.pivot_table(data, index="grade", columns='prod_cd', values='pch_amt', aggfunc=np.mean)

pd.pivot_table(data, index="grade", columns='prod_cd', values='pch_amt', aggfunc=np.sum)

#data.pivot(index="grade", columns='prod_cd', values='pch_amt')#에러

ValueError: Index contains duplicate entries, cannot reshape

In [103]:
# stack():위에서 아래로 쌓는 것
# unstack():쌓여 있는 것을 옆으로 놓는것(왼->오)
mul_index = pd.MultiIndex.from_tuples([('cust_1', '2020'), ('cust_1', '2021'),
   ('cust_2', '2020'), ('cust_2', '2021')])  
mul_index

data = pd.DataFrame(data=np.arange(16).reshape(4, 4),
index=mul_index, columns=['prd_1', 'prd_2', 'prd_3', 'prd_4'],
dtype='int')

data

prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2      3
       2021      4      5      6      7
cust_2 2020      8      9     10     11
       2021     12     13     14     15

In [104]:
datastd=data.stack()
datastd

cust_1  2020  prd_1     0
              prd_2     1
              prd_3     2
              prd_4     3
        2021  prd_1     4
              prd_2     5
              prd_3     6
              prd_4     7
cust_2  2020  prd_1     8
              prd_2     9
              prd_3    10
              prd_4    11
        2021  prd_1    12
              prd_2    13
              prd_3    14
              prd_4    15
dtype: int32

In [105]:
datastd.index

MultiIndex([('cust_1', '2020', 'prd_1'),
            ('cust_1', '2020', 'prd_2'),
            ('cust_1', '2020', 'prd_3'),
            ('cust_1', '2020', 'prd_4'),
            ('cust_1', '2021', 'prd_1'),
            ('cust_1', '2021', 'prd_2'),
            ('cust_1', '2021', 'prd_3'),
            ('cust_1', '2021', 'prd_4'),
            ('cust_2', '2020', 'prd_1'),
            ('cust_2', '2020', 'prd_2'),
            ('cust_2', '2020', 'prd_3'),
            ('cust_2', '2020', 'prd_4'),
            ('cust_2', '2021', 'prd_1'),
            ('cust_2', '2021', 'prd_2'),
            ('cust_2', '2021', 'prd_3'),
            ('cust_2', '2021', 'prd_4')],
           )

In [111]:
datastd['cust_2']['2020'][['prd_1','prd_2']]

prd_1    8
prd_2    9
dtype: int32

In [129]:
data.ix['cust_2', 'prd_4']=np.nan
data

C:\Users\student\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


prd_1  prd_2  prd_3  prd_4
cust_1 2020      0      1      2    3.0
       2021      4      5      6    7.0
cust_2 2020      8      9     10    NaN
       2021     12     13     14    NaN

In [131]:
data.stack() #nan은 출력이 되지 않음
data.stack(dropna=False) 

cust_1  2020  prd_1     0.0
              prd_2     1.0
              prd_3     2.0
              prd_4     3.0
        2021  prd_1     4.0
              prd_2     5.0
              prd_3     6.0
              prd_4     7.0
cust_2  2020  prd_1     8.0
              prd_2     9.0
              prd_3    10.0
              prd_4     NaN
        2021  prd_1    12.0
              prd_2    13.0
              prd_3    14.0
              prd_4     NaN
dtype: float64

In [132]:
#melt
data = pd.DataFrame({'cust_ID' : ['C_001', 'C_001', 'C_002', 'C_002'],
   'prd_CD' : ['P_001', 'P_002', 'P_001', 'P_002'],
   'pch_cnt' : [1, 2, 3, 4],'pch_amt' : [100, 200, 300, 400]})

In [133]:
data

cust_ID prd_CD  pch_cnt  pch_amt
0   C_001  P_001        1      100
1   C_001  P_002        2      200
2   C_002  P_001        3      300
3   C_002  P_002        4      400

In [135]:
pd.melt(data, id_vars=['cust_ID', 'prd_CD'])

pd.melt(data, id_vars=['cust_ID', 'prd_CD'], var_name='CD', value_name='VAL')

cust_ID prd_CD       CD  VAL
0   C_001  P_001  pch_cnt    1
1   C_001  P_002  pch_cnt    2
2   C_002  P_001  pch_cnt    3
3   C_002  P_002  pch_cnt    4
4   C_001  P_001  pch_amt  100
5   C_001  P_002  pch_amt  200
6   C_002  P_001  pch_amt  300
7   C_002  P_002  pch_amt  400

In [137]:
pew=pd.read_csv("pew.csv")
pew.head()
pew.iloc[:,0:6]

religion  <$10k  $10-20k  $20-30k  $30-40k  $40-50k
0                  Agnostic     27       34       60       81       76
1                   Atheist     12       27       37       52       35
2                  Buddhist     27       21       30       34       33
3                  Catholic    418      617      732      670      638
4        Don’t know/refused     15       14       15       11       10
5          Evangelical Prot    575      869     1064      982      881
6                     Hindu      1        9        7        9       11
7   Historically Black Prot    228      244      236      238      197
8         Jehovah's Witness     20       27       24       24       21
9                    Jewish     19       19       25       25       30
10            Mainline Prot    289      495      619      655      651
11                   Mormon     29       40       48       51       56
12                   Muslim      6        7        9       10        9
13                 Orthodox     13       17       23       32       32
14          Other Christian      9        7       11       13       13
15             Other Faiths     20       33       40       46       49
16    Other World Religions      5        2        3        4        2
17             Unaffiliated    217      299      374      365      341

In [139]:
pd.melt(pew, id_vars='religion', var_name='income', value_name='count')

religion              income  count
0                 Agnostic               <$10k     27
1                  Atheist               <$10k     12
2                 Buddhist               <$10k     27
3                 Catholic               <$10k    418
4       Don’t know/refused               <$10k     15
..                     ...                 ...    ...
175               Orthodox  Don't know/refused     73
176        Other Christian  Don't know/refused     18
177           Other Faiths  Don't know/refused     71
178  Other World Religions  Don't know/refused      8
179           Unaffiliated  Don't know/refused    597

[180 rows x 3 columns]

In [140]:
billboard=pd.read_csv("billboard.csv")
billboard

year            artist                    track  time date.entered  wk1  \
0    2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   87   
1    2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   91   
2    2000      3 Doors Down               Kryptonite  3:53   2000-04-08   81   
3    2000      3 Doors Down                    Loser  4:24   2000-10-21   76   
4    2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   57   
..    ...               ...                      ...   ...          ...  ...   
312  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   86   
313  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   85   
314  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   95   
315  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   99   
316  2000   matchbox twenty                     Bent  4:12   2000-04-29   60   

      wk2   wk3   wk4   wk5  ...  wk67  wk68  wk69  wk70  wk71  wk72  wk73  \
0    82.0  72.0  77.0  87.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
1    87.0  92.0   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
2    70.0  68.0  67.0  66.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
3    76.0  72.0  69.0  67.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
4    34.0  25.0  17.0  17.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
..    ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...   ...   
312  83.0  77.0  74.0  83.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
313  83.0  83.0  82.0  81.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
314  94.0  91.0  85.0  84.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
315  99.0   NaN   NaN   NaN  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   
316  37.0  29.0  24.0  22.0  ...   NaN   NaN   NaN   NaN   NaN   NaN   NaN   

     wk74  wk75  wk76  
0     NaN   NaN   NaN  
1     NaN   NaN   NaN  
2     NaN   NaN   NaN  
3     NaN   NaN   NaN  
4     NaN   NaN   NaN  
..    ...   ...   ...  
312   NaN   NaN   NaN  
313   NaN   NaN   NaN  
314   NaN   NaN   NaN  
315   NaN   NaN   NaN  
316   NaN   NaN   NaN  

[317 rows x 81 columns]

In [144]:
billboard.columns
pd.melt(billboard, id_vars=['year', 'artist', 'track', 'time', 'date.entered'], var_name="week", value_name="rating")

year            artist                    track  time date.entered  \
0      2000             2 Pac  Baby Don't Cry (Keep...  4:22   2000-02-26   
1      2000           2Ge+her  The Hardest Part Of ...  3:15   2000-09-02   
2      2000      3 Doors Down               Kryptonite  3:53   2000-04-08   
3      2000      3 Doors Down                    Loser  4:24   2000-10-21   
4      2000          504 Boyz            Wobble Wobble  3:35   2000-04-15   
...     ...               ...                      ...   ...          ...   
24087  2000       Yankee Grey     Another Nine Minutes  3:10   2000-04-29   
24088  2000  Yearwood, Trisha          Real Live Woman  3:55   2000-04-01   
24089  2000   Ying Yang Twins  Whistle While You Tw...  4:19   2000-03-18   
24090  2000     Zombie Nation            Kernkraft 400  3:30   2000-09-02   
24091  2000   matchbox twenty                     Bent  4:12   2000-04-29   

       week  rating  
0       wk1    87.0  
1       wk1    91.0  
2       wk1    81.0  
3       wk1    76.0  
4       wk1    57.0  
...     ...     ...  
24087  wk76     NaN  
24088  wk76     NaN  
24089  wk76     NaN  
24090  wk76     NaN  
24091  wk76     NaN  

[24092 rows x 7 columns]

In [157]:
s=pd.Series(range(10))
s[3]=np.nan
s
s.count() #9, 누락값은 제외

df=pd.DataFrame(np.random.randint(5,size=(4,4)),dtype=float)
df.iloc[2,3]=np.nan
df
#df.count() #4,4,4,3 (각 열의 데이터 갯수)

import seaborn as sns
titanic=sns.load_dataset("titanic")
titanic.head()
titanic.count()

survived       891
pclass         891
sex            891
age            714
sibsp          891
parch          891
fare           891
embarked       889
class          891
who            891
adult_male     891
deck           203
embark_town    889
alive          891
alone          891
dtype: int64

In [166]:
np.random.seed(777)
s2=pd.Series(np.random.randint(6, size=100))
s2
#s2.count()
s2.value_counts()
#종류별로 데이터 갯수를 count
df[0].value_counts()

1.0    2
4.0    1
0.0    1
Name: 0, dtype: int64

In [169]:
s2.value_counts().sort_index()#인덱스 기준 정렬

0    20
1    11
2    15
3    15
4    19
5    20
dtype: int64

In [179]:
s.sort_values() #값을 기준으로 정렬(nan은 맨 마지막)
s.sort_values(ascending=False)
df.sort_values(by=3)

df.sort_values(by=[1,2])

0    1    2    3
3  4.0  0.0  2.0  3.0
2  0.0  1.0  0.0  NaN
1  1.0  1.0  4.0  0.0
0  1.0  2.0  4.0  2.0

In [183]:
df=pd.DataFrame(np.random.randint(10,size=(4,8)))
df
df["Mysum"]=df.sum(axis=1)
df

0  1  2  3  4  5  6  7  Mysum
0  8  1  8  7  7  2  4  3     40
1  6  5  0  2  5  2  4  3     27
2  9  4  4  3  0  3  0  5     28
3  3  0  1  9  3  8  7  4     35

In [186]:
df.sum()

0         26
1         10
2         13
3         21
4         15
5         15
6         15
7         15
Mysum    130
dtype: int64

In [187]:
df.loc["total", :]=df.sum()
df

0     1     2     3     4     5     6     7  Mysum
0       8.0   1.0   8.0   7.0   7.0   2.0   4.0   3.0   40.0
1       6.0   5.0   0.0   2.0   5.0   2.0   4.0   3.0   27.0
2       9.0   4.0   4.0   3.0   0.0   3.0   0.0   5.0   28.0
3       3.0   0.0   1.0   9.0   3.0   8.0   7.0   4.0   35.0
total  26.0  10.0  13.0  21.0  15.0  15.0  15.0  15.0  130.0

In [189]:
#실수 데이터 -> 카테고리화
#cut(실수 값의 경계 지정), 
#qcut(똑같은 구간으로 나눔)
ages=[0,2,10,21,23,37,31,61,20,42,32,100]
bins=[1,15,25,35,60,99]
labels=["미성년자", "청년","중년","장년","노년"]
cats=pd.cut(ages, bins, labels=labels)
cats

[NaN, 미성년자, 미성년자, 청년, 청년, ..., 노년, 청년, 장년, 중년, NaN]
Length: 12
Categories (5, object): [미성년자 < 청년 < 중년 < 장년 < 노년]

In [191]:
cats.categories
cats.codes

array([-1,  0,  0,  1,  1,  3,  2,  4,  1,  3,  2, -1], dtype=int8)

In [196]:
df=pd.DataFrame(ages, columns=["ages"])
df['age_cat']=pd.cut(ages, bins, labels=labels)
df

ages age_cat
0      0     NaN
1      2    미성년자
2     10    미성년자
3     21      청년
4     23      청년
5     37      장년
6     31      중년
7     61      노년
8     20      청년
9     42      장년
10    32      중년
11   100     NaN

In [199]:
data=np.random.randn(100)
data
cats=pd.qcut(data, 4, labels=["Q1","Q2","Q3","Q4"])
cats
pd.value_counts(cats)

Q4    25
Q3    25
Q2    25
Q1    25
dtype: int64