In [1]:
#배열 축 추가:np.newaxis, np.tile()
import numpy as np

In [3]:
a=np.array([1,2,3,4])
a
a.shape

(4,)

In [6]:
a41=a[np.newaxis,:]
a41.shape

(1, 4)

In [11]:
b=np.arange(15).reshape(3,5)
b
b351=b[:,:,np.newaxis]
b351.shape

b315=b[:,np.newaxis,:]
b315.shape

(3, 1, 5)

In [16]:
a=np.array([0,1,2,3])
a8=np.tile(a,2)
a8

a32=np.tile(a,(3,2))
a32

b=np.arange(8).reshape(2,4)
b28=np.tile(b,2)
b28

b44=np.tile(b,(2,1))
b44

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

In [19]:
#행렬의 내적 : aT * a
a=np.arange(15).reshape(3,5)
a.T
np.transpose(a)

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [23]:
a=np.arange(10)
a
ai=a[0:5]
ai[1:3]=10
ai
a

array([ 0, 10, 10,  3,  4,  5,  6,  7,  8,  9])

In [24]:
# df1(전반기)
# df2(하반기)
# df3=pd.concat([df1,df2])
# pd.concat([df3, pd.DataFrame({"매출":df3['매출'].sum,... })], index=["총실적"])

In [26]:
arr=np.arange(20).reshape(5,4)
arr
abc=np.array(['a','a','b','c','c'])

In [46]:
arr[abc=='a']
arr[abc=='a',:]

arr[abc=='a',:2]
arr[abc=='a',2]

arr[abc!='a']
arr[~(abc=='a')]

arr[(abc=="a") | (abc=="b")]

arr[(abc!="a") & (abc!="b")]

# arr에서 abc배열을 이용하여 'a'와 같은 행은
# 모두 99로 변경(불린 참조)
arr[abc=='a']=99

In [47]:
arr

array([[99, 99, 99, 99],
       [99, 99, 99, 99],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [50]:
#arr배열에서 20보다 큰 값은 모두 0으로 변경
arr[arr>=20]=0

In [61]:
arr
#arr배열에서 8이상 15이하의 값은 모두 10으로 변경

#arr[8<=arr<=15] #valueError
#arr[8<=arr & arr<=15] #valueError
arr[(8<=arr) & (arr<=15)]

array([ 8,  9, 10, 11, 12, 13, 14, 15])

In [71]:
a=np.array([-3.5, -2.2, 0, 1.6, 3.14, 4.05])
np.around(a) #0.5기준 내림 혹은 올림
np.round_(a,1) #소수이하 첫째짜리
np.rint(a) #가까운 정수로 올림 또는 내림
np.fix(a) #0 방향으로 가까운 정수로 올림 또는 내림
np.ceil(a) #값보다 크거나 같은 가장 
#작은 정수값으로 올림
np.floor(a)#값보다 작거나 같은 가장 
#큰 정수값으로 내림
np.trunc(a) #소수 이하 버림

array([-3., -2.,  0.,  1.,  3.,  4.])

In [74]:
a=np.array([1,2,3,4])
c=np.arange(1,5).reshape(2,2)

In [79]:
#배열 요소값 곱셈
np.prod(c) #24
np.prod(c, axis=0)
np.prod(c, axis=1)

array([ 2, 12])

In [86]:
np.sum(a) #0차원, 스칼라
a
np.sum(a, keepdims=True)
np.sum(c,axis=0)
np.sum(c,axis=1)

array([3, 7])

In [92]:
d=np.array([[1,2], [3,np.nan]])
d
np.prod(d)
np.prod(d,axis=0)
np.prod(d,axis=1)

#np.nanprod:곱셈할때 nan을 1로 간주해서 곱셈
np.nanprod(d, axis=0)


array([3., 2.])

In [95]:
d
np.sum(d)
np.nansum(d)#nan은 0으로 취급

6.0

In [100]:
a
b=np.arange(1,7).reshape(2,3)
b
np.cumprod(a)
np.cumprod(b)
np.cumprod(b,axis=0)

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [102]:
#자연상수e, y=logx or y=ln(x)
#지수함수 : np.exp(), 
#밑이 자연상수 e인 지수함수로 변환

x=np.array([0.00001, 1, 2, 10])
np.exp(x)

np.log(x)
np.log10(x)
np.log2(x)

array([-11.51292546,   0.        ,   0.69314718,   2.30258509])