In [3]:
# 배열 축 추가
import numpy as np

a = np.array([1,2,3,4])
a.shape

(4,)

In [7]:
a41 = a[:,np.newaxis] # 새로운 축을 설정할 수 있다.
print(a41.shape)
a41

(4, 1)


array([[1],
       [2],
       [3],
       [4]])

In [9]:
a14 = a[np.newaxis,:]
print(a14.shape)
a14

(1, 4)


array([[1, 2, 3, 4]])

In [13]:
b = np.arange(15).reshape(3,5)
print(b.shape)
b

(3, 5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [14]:
b351 = b[:,:,np.newaxis]
print(b351.shape)
b351

(3, 5, 1)


array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9]],

       [[10],
        [11],
        [12],
        [13],
        [14]]])

In [15]:
b315 = b[:,np.newaxis,:]
print(b315.shape)
b315

(3, 1, 5)


array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])

* tile 함수를 사용해서 반복되는 array를 만들 수 있다.

In [19]:
a = np.arange(4)
a8 = np.tile(a,2)
a8

array([0, 1, 2, 3, 0, 1, 2, 3])

In [22]:
a32 = np.tile(a,(3,2)) #튜플 형태로 입력을 넣으면 행 방향으로 3회, 열 방향으로 2회
a32

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3],
       [0, 1, 2, 3, 0, 1, 2, 3]])

In [25]:
b = np.arange(8).reshape(2,4)
b28 = np.tile(b,2)
b28

array([[0, 1, 2, 3, 0, 1, 2, 3],
       [4, 5, 6, 7, 4, 5, 6, 7]])

In [26]:
b44 = np.tile(b,(2,1))
b44

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [0, 1, 2, 3],
       [4, 5, 6, 7]])

* 행렬의 transpose

In [29]:
# 행렬의 내적 : aT * a
a = np.arange(15).reshape(3,5) 
a.T # a의 transpose 구할 수 있다.
np.transpose(a) # transpose 함수를 사용해도 같은 결과를 얻을 수 있다.

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

* 참조

In [34]:
a = np.arange(10)
ai = a[:5]
ai[1:3] = 10
print(ai)  # ai가 가르키는 것이 a가 가르키는 것과 동일해서
print(a)   # a도 값이 바뀌게된다. 참조의 개념

[ 0 10 10  3  4]
[ 0 10 10  3  4  5  6  7  8  9]


In [44]:
arr = np.arange(20).reshape(5,4)
abc = np.array(list('aabcc'))
print(abc == 'a')
arr[abc == 'a'] # 행 단위로 2개의 행이 True이므로 출력되고 나머지는 False라서 출력되지 않음
arr[abc == 'a',:2] # 행 단위 2개 출력하고, 해당열을 :2 까지만 출력

[ True  True False False False]


array([[0, 1],
       [4, 5]])

In [45]:
arr[abc != 'a']

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [48]:
arr[abc == 'a'] = 99
arr[arr > 20] = 0
arr

array([[ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [52]:
a = np.array([-3.5,-2.2,0,1.6,3.14,4.05])
np.around(a)
np.round_(a,1) # 소수이하 첫째짜리까지
np.rint(a) # 가까운 정수로 올림 또는 내림
np.fix(a) # 0 방향으로 가까운 정수로 올림 또는 내림
np.ceil(a) # 값보다 크거나 같은 가장 작은 정수 값으로 올림
np.floor(a) # 값보다 작거나 같은 가장 큰 정수 값으로 내림

array([-4., -3.,  0.,  1.,  3.,  4.])

In [55]:
a = np.array([1,2,3,4])
c = np.arange(1,5).reshape(2,2)
c

array([[1, 2],
       [3, 4]])

In [58]:
np.prod(c) # 24 전체 요소들 간의 곱
np.prod(c, axis = 0) # 열 방향으로 곱
np.prod(c, axis = 1) # 행 방향으로 곱

array([ 2, 12])

In [64]:
np.sum(a) # 0차원, 스칼라
np.sum(c, axis = 0) # 1차원

array([4, 6])

In [73]:
d = np.array([[1,2],[3,np.nan]])
d
np.prod(d)
np.prod(d, axis = 0)
np.prod(d, axis = 1)
# nan을 포함하고 있어서 곱에 nan 값이 나옴
# nan 이 안나오게 하고싶으면
# np.nanprod : 곱셈할 때 nan을 1로 간주해서 곱셈
np.nanprod(d, axis = 0)

# sum 또한 마찬가지 nan을 0으로 간주해서 합함
np.nansum(d, axis = 0)

array([4., 2.])

In [74]:
b = np.arange(1,7).reshape(2,3)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
a

array([1, 2, 3, 4])

In [77]:
np.cumprod(a)

array([ 1,  2,  6, 24], dtype=int32)

In [81]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [78]:
np.cumprod(b) # 누적 곱

array([  1,   2,   6,  24, 120, 720], dtype=int32)

In [83]:
np.cumprod(b, axis = 0) # 열 단위로 누적 곱

array([[ 1,  2,  3],
       [ 4, 10, 18]], dtype=int32)

In [84]:
# cumsum 또한 동일, 누적 합을 출력

지수함수

자연상수e : y = logx or y=ln(x)
지수함수 : np.exp() : 밑이 자연상수 e인 지수함수로 변환

In [85]:
x = np.array([0.00001,1,2,10])
np.exp(x)

array([1.00001000e+00, 2.71828183e+00, 7.38905610e+00, 2.20264658e+04])

In [86]:
np.log(x)

array([-11.51292546,   0.        ,   0.69314718,   2.30258509])