데이터 전처리

전처리 : 결측치를 어떻게 대처할 것인가가 중요
무조건 없애면 데이터가 부족해서 못하는 경우도 발생
어떤 값으로 대체를 하는 것이 없애는 것보다 낫다.
knn 알고리즘이나 회귀분석으로 예측된 값을 대체하는 경우 등


정규화 : 각 점수의 최소와 최대 사이를 0과 1 사이로 만듬
컴퓨터는 숫자만 받아들임
표준화 : 평균을 0으로, 표준편차를 1로 표현

원핫인코딩 : 100000,010000,001000, ...    
분류를 해야되는 문제에서 분류 결과에 대해서    
             A    B    C   D  E  F   
문장 추출 -> 단어(5개) 추출 -> 원핫인코딩    
국어10000   
영어01000     
수학00100     
과학00010    
윤리00001   

각 단어들을 컴퓨터가 구분하기 위함   
원 핫 인코딩 => 메모리 낭비가 매우 심하고 연산도 길어짐
데이터가 커지면 커질수록 매우 복잡함
단어의 갯수만큼 차원의 공간이 필요해지므로 매우 낭비


문장 추출 -> 단어(5개) 추출 -> 밀집 벡터 word2vec
국어 [0.2  0.7]
수학 [0.1, 0.3]
==> 차원이 줄어들었음
==> 각 축의 의미가 무었인가? 데이터들의 일반화된 특성일 것으로 추축 정확히 무엇인지알지 못함

리스트 : 속도느림, 메모리 많이 차지
배열(array) : 속도빠름, 메모리 적게 차지
넘파이 배열 

넘파이와 배열과 리스트의 차이점
- 배열은 모두 같은 자료형, 원소 개수 변경 못함
- 배열은 파이썬에서 제공하지 않음
- 파이썬 환경에서 넘파이 패키지를 활용하여 배열을 사용할 수 있음

넘파이 수치해석 패키지, 다차원 배열 구조 백터, 행렬을 ㅏ용하는 선형대수 계산시 사용, 넘파이 배열 연산 빠름 (벡터화 연산)

In [3]:
import numpy as np

ar = np.array([0,1,2,3,4])
type(ar)

numpy.ndarray

In [4]:
ar

array([0, 1, 2, 3, 4])

100 * 100 크기의 이미지(픽셀 : 10000개)
0~255 사이의 gray scale   
=> 1만 개의 축이 있는 것
=> 1만 차원, 10000 Dimension

In [14]:
data = list(range(0,10))

In [15]:
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
data = np.array(data) * 2
# NUMPY는 벡터 연산을 사용함
# FOR문을 사용하지 않음
# 계산 속도가 매우 빨라짐

In [17]:
list(data)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

### 시간복잡도(CPU)
* 연산 결과가 나오기까지 수행되는 라인의 수   

sum = 0
for d in data:
    sum += d
print (sum) 

=>> 100개면 연산 100번 해야함

ㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡㅡ

print(d*d+1)/2)  ==>> 한 줄 연산으로 결과 출력
매우 효율적인 방법 매우 빠르게 결과 출력!

### 공간복잡도(MEM) 
* 메모리가 얼마나 필요한지, 메모리를 차지하는 정도


In [18]:
a = np.array([1,2,3])
b = np.array([4,5,6])
a2 = [1,2,3]
b2 = [4,5,6]

In [21]:
2*a2+b2 # list는 연산이 append 형식

[1, 2, 3, 1, 2, 3, 4, 5, 6]

In [22]:
2*a + b # array는 백터 연산

array([ 6,  9, 12])

In [30]:
x = np.array([[0,1,2],[3,4,5]])
print(x)
# 열 : 안쪽 리스트 길이, 가로 크기
# 행 : 바깥쪽 리스트 길이, 세로 크기
# 0 1 2
# 3 4 5

[[0 1 2]
 [3 4 5]]


In [87]:
# array slicing
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar[0,:]) # 첫번째 행 전체
print(ar[:,1]) # 두번째 열 전체
print(ar[1,1:])  # 두번째 행 부터 마지막까지
print(ar[:2,:2])

[1 2 3 4]
[2 6]
[6 7 8]
[[1 2]
 [5 6]]


6


# 불린 참조 
매우중요
조건에 대한 만족하는 값을 추출


In [90]:
ar=np.array([2,3,4,5])
bidx=np.array([True,True,False,True])
ar[bidx]
# True에 해당하는 array를 가져오는 불린 참조

array([2, 3, 5])

In [91]:
ar[ar != 4]

array([2, 3, 5])

In [93]:
ar[ar% 2 == 0]

array([2, 4])

In [95]:
#정수 참조 추출
ar = np.array([2,3,4,5])
idx = np.array([0,3])
ar[idx]

array([2, 5])

In [145]:
ar = np.array([[1,2,3,4],[5,6,7,8]])
print(ar)
#[[1,4],
#  5,8]]
ar[:,[0,3]]
ar[:,[True,False,False,True]]

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 4],
       [5, 8]])

In [150]:
ar = np.array([[1,2,3,4],
              [15,26,37,48],
              [25,26,27,28],
              [31,32,33,34]])
ar[[2,0,-1],:]

array([[25, 26, 27, 28],
       [ 1,  2,  3,  4],
       [31, 32, 33, 34]])

In [151]:
# http://pandas.pydata.org >> 참고 사이트
import pandas as pd
csvTest = pd.read_csv("test_csv.csv")
csvTest

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [156]:
text = pd.read_csv("test_text.txt",sep='|')
text

ID LAST_NAME  AGE
0   1       KIM   25
1   2       LEE   22
2   3      PARK   33
3   4      CHOI   24
4   5       CHO   30

In [79]:
#1 다음 데이터에서 연속으로 숫자 3개를 곱했을때 얻어진
# 결과값이 가장 큰 구간이 어디인지 출력
x = [3,2,1,-4,-7,-9,8,-5,3,-1]
dic = {}
maxv = 0
dic = {}
for i in range(len(x)-2):
    dic['%s' % str(i)] = multi(x[i:i+3])

for i in dic:
    if dic[i] == max(dic.values()):
        n = int(i)
        print(x[n:n+3], max(dic.values()))


    


[-7, -9, 8] 504
