# Map

map(Function, Data) : 데이터에 대해서 함수를 적용해라

In [1]:
x, y = map(int, input("문자열 두개 입력 : ").split())
print(x + y)

문자열 두개 입력 : 5 10
15


# Numpy

In [2]:
import numpy as np

In [3]:
data = np.random.randn(2,3)

In [4]:
data

array([[ 0.42080323,  1.40700543, -1.97247841],
       [-0.05338324,  0.50660943, -0.11949815]])

In [5]:
data += data

In [6]:
data

array([[ 0.84160647,  2.81401086, -3.94495682],
       [-0.10676648,  1.01321885, -0.2389963 ]])

In [8]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [11]:
arr_slice[1] = 12345
arr_slice

array([    5, 12345,     7])

In [12]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

* arr_slice의 배열이 바뀌자 원본 배열인 arr도 변경된 것을 확인할 수 있다.

* 슬라이스 복사본을 얻고 싶으면 copy해서 사용해야한다.

In [13]:
arr_slice2 = arr[5:8].copy()
arr_slice2

array([    5, 12345,     7])

In [14]:
arr_slice2[1] = 6
arr_slice2

array([5, 6, 7])

In [15]:
arr

array([    0,     1,     2,     3,     4,     5, 12345,     7,     8,
           9])

In [21]:
arr = np.arange(15).reshape((3,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

* 행열 Transpose

In [22]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

* 행렬의 내적 : np.dot

In [23]:
np.dot(arr.T,arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])