In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.15.0'

In [3]:
# placeholder : 프로그램 실행 중에 값을 변경할 수 있는 버퍼 
# 데이터를 임시로 담는 버퍼같은 역할  
a = tf.placeholder('float')  
b = tf.placeholder('float') 

In [4]:
y = tf.multiply(a, b)
# 그래프 실행을 위해서는 세션이 필요
sess = tf.Session()

# tensorflow에서 노드는 연산이라고 생각하면 됨

# y 노드를 실행
sess.run(y, feed_dict={a:3, b:2})

6.0

In [5]:
ho = tf.constant('hellow')
print(ho)
sess = tf.Session()
print(sess.run(ho))

Tensor("Const:0", shape=(), dtype=string)
b'hellow'


In [6]:
a = tf.constant(10)
b = tf.constant(20)

In [7]:
print(a)

Tensor("Const_1:0", shape=(), dtype=int32)


In [8]:
sess.run(a)

10

In [9]:
tf.add(a,b)

<tf.Tensor 'Add:0' shape=() dtype=int32>

In [10]:
print(tf.Session().run(tf.add(a,b)))
tf.Session().close()

30


In [11]:
a = tf.placeholder(dtype='float')
b = tf.placeholder(tf.float32)

In [12]:
adderNode = a + b
print(adderNode)

Tensor("add_2:0", dtype=float32)


In [13]:
s = tf.Session()
# triple = 3 * adderNode
triple = tf.multiply(tf.add(a,b),3)
s.run(triple, feed_dict={a:[3,4],b:[2,7]}) 

array([15., 33.], dtype=float32)

In [14]:
w = tf.Variable([[1],[2]])

In [15]:
xdata = [[1,2,3],[4,5,6]]
# hf = x * w + b
# x shape  = (2,3) * (3, 1) = (2, 1)
# b = (1)
x = tf.placeholder(tf.float32, [None,3])
w = tf.Variable([[1],[2],[4]])
b = tf.Variable([9])

hf = tf.add(tf.matmul(xdata, w),b)

sess.run(tf.global_variables_initializer())
sess.run(hf)

array([[26],
       [47]])

In [16]:
xdata = [[1,2,3],[4,5,6]]
x = tf.placeholder(tf.float32, [None,3])
w = tf.Variable(
        tf.random_normal([3,1]))
b = tf.Variable(
        tf.random_normal([1]))
hf = tf.matmul(x,w) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(hf, feed_dict={x:xdata})

array([[ 0.64786935],
       [-2.2788959 ]], dtype=float32)