# Problem 01

#1 연속으로 숫자 3개를 곱했을때 얻어지는 결과 값이 가장 큰 구간이 어디인지 출력하시오

In [1]:
import numpy as np

def multi(s):
    multi = 1
    for i in s:
        multi *= i
    return multi

x=np.array([3,2,1,-4,-7,-9,8,-5,3,-1])
dic = {}
maxv = 0
for i in range(len(x)-2):
    dic['%s' % str(i)] = multi(x[i:i+3])

for i in dic:
    if dic[i] == max(dic.values()):
        n = int(i)
        print(x[n:n+3], max(dic.values()))

[-7 -9  8] 504


# Problem 02

#2 2*2의 영역을 구성하는 수를 모두 곱했을때 얻어지는 결과값이 가장 큰 구간이 어디인지 출력하시오



In [2]:
ar=np.array([[3,1,2],[2,1,-3],[-2,0,-7]])

row, col = ar.shape
max_val = 0
for i in range(row-1):
     for j in range(col-1):
        val = ar[i][j]*ar[i][j+1]*ar[i+1][j]*ar[i+1][j+1] 
        if max_val < val:
            max_val = val
            place = ar[i:i+2,j:j+2]
print(max_val)
print(place)

6
[[3 1]
 [2 1]]


# Problem 03

다음 행렬과 같은 행렬이 있다.

m = np.array([[ 0,  1,  2,  3,  4],    
              [ 5,  6,  7,  8,  9],    
              [10, 11, 12, 13, 14]])    
이 행렬에서 값 7 을 인덱싱한다.    
이 행렬에서 값 14 을 인덱싱한다.    
이 행렬에서 배열 [6, 7] 을 슬라이싱한다.    
이 행렬에서 배열 [7, 12] 을 슬라이싱한다.    
이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.    

In [3]:
import numpy as np
import pandas as pd

m = np.array([[ 0,  1,  2,  3,  4],
              [ 5,  6,  7,  8,  9],
              [10, 11, 12, 13, 14]])

In [4]:
m[1,2]

7

In [5]:
m[-1,-1]

14

In [6]:
m[1,1:3]

array([6, 7])

In [7]:
m[1:,2]

array([ 7, 12])

In [8]:
m[:2,-2:]

array([[3, 4],
       [8, 9]])

# Problem 04

다음 행렬과 같은 배열이 있다.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,     
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])     
이 배열에서 3의 배수를 찾아라.     
이 배열에서 4로 나누면 1이 남는 수를 찾아라.     
이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.     

In [9]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [10]:
x3 = x[x % 3 == 0]
x3

array([ 3,  6,  9, 12, 15, 18])

In [11]:
x4 = x[x % 4 == 1]
x4

array([ 1,  5,  9, 13, 17])

In [12]:
np.intersect1d(x3,x4)

array([9])

# Problem 05

90도 회전시 벽돌 이동거리가 최대인 값 출력

In [13]:
box_height = np.array([7,4,2,0,0,6,0,7,0])
row = 8
col = len(box_height)
max_len = 0 # 초기화
for i in range(1,row+1): # 행
    for j in range(1,col+1): # 열
        if box_height[j-1] - (i) < 0: # 해당 열에서 박스 높이만큼 빼서
            continue                 # 해당 열에 박스가 있는지 확인
        under_boxes = box_height[j:][box_height[j:] >= i] # 아래 박스의 갯수
        move_len = (col-j) - len(under_boxes) # 이동거리 = 기존자리 - 아래 박스갯수 
        max_len = max(col-j - len(under_boxes),max_len) #가장 큰 친구 값 저장
print(max_len)

7
