In [1]:
import tensorflow as tf

In [2]:
a=tf.placeholder("float")
b=tf.placeholder("float")
#플레이스홀더:프로그램 실행 중에 값을 변경할
#수 있는 변수를 2개 정의
#데이터를 담는 버퍼와 같은 것


In [3]:
y=tf.multiply(a,b)
sess=tf.Session() 
#그래프 실행을 위해서는 세션이 필요
print(sess.run(y,feed_dict={a:3,b:2}))
#y노드를 실행해라

6.0


In [ ]:
tensorflow.org


In [5]:
hello=tf.constant("Hello")
sess=tf.Session()
print(sess.run(hello))

b'Hello'


In [6]:
3 #랭크:0 tensor, shape:[]
[1,2,3] #랭크:1,  shape:[3]
[[1,2,3],[1,2,3]] #랭크:2, shape:[2,3]
[[[1,2,3]],[[4,5,6]]]
#랭크:3, shape:[2,1,3]

3

In [17]:
a=tf.constant(10)
b=tf.constant(20)
sess=tf.Session()
#print(sess.run(tf.add(a,b)))
c=tf.add(a,b)
#print(sess.run(c))
#print(c)
print(sess.run(a))
print(sess.run(b))
print(sess.run([a,b]))
sess.close()

10
20
[10, 20]


In [28]:
a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)
adderNode=a+b
sess=tf.Session()
print(sess.run(adderNode, feed_dict={a:[5,1],b:[3,2]}))
# print(sess.run(adderNode, feed_dict={a:1,b:2}))

[8. 3.]


In [31]:
# a=2, b=3
# =>5 * 3 => 15가 출력되도록 노드 정의
triple=adderNode*3 #구현
print(sess.run(triple,feed_dict={a:2, b:3}))



15.0


In [40]:
x=tf.placeholder(tf.float32,[None,3])
#print(x)
xdata=[[1,2,3],[4,5,6]]
#xdata2=[[1,2,3,4],[4,5,4,5]] 에러
print(sess.run(x, feed_dict={x:xdata}))
#print(sess.run(x, feed_dict={x:xdata2}))

[[1. 2. 3.]
 [4. 5. 6.]]


In [42]:
#H(x)=wx+b
#w=tf.Variable(tf.random_normal([2,1]))
w=tf.Variable([[1],[2]])
#hf=tf.matmul(x,w)+b

In [46]:
xdata=[[1,2,3], #2행 3열(국어,영어,수학)
      [4,5,6]]
x=tf.placeholder(tf.float32, [None,3])
w=tf.Variable(
    tf.random_normal([3,1]))#각 과목 가중치
b=tf.Variable(
    tf.random_normal([1])) #편향
hf=tf.matmul(x,w)+b
sess=tf.Session()
# hf=xw+b
# hf실행
sess.run(tf.global_variables_initializer())
print(sess.run(hf,feed_dict={x:xdata}))
#x shape=>(2,3) * (3,1) => (2,1)
#w shape =>?

[[0.32572913]
 [1.3988826 ]]


In [ ]:
#선형 회귀 모델

In [84]:
xtrain=[80, 95, 97] #모의고사 점수(3명)
ytrain=[82, 90, 98] #수능점수(3명)
#모의고사 70점 -> 수능?
#hf= x*w+b
#82=80*1+2
#90=95*0.9+1

In [85]:
w=tf.Variable(tf.random_normal([1]))
b=tf.Variable(tf.random_normal([1]))

In [86]:
hf=xtrain*w+b

In [87]:
sess=tf.Session()
sess.run(tf.global_variables_initializer())

In [88]:
print(sess.run([w,b,hf]))#[80, 95, 97]
#w=-0.35, b=0.49
#hf(예상)=[-27,-33,-33]    hf=xtrain*w+b
    #정답=[82, 90, 98]
#cost=((-27-82)^2+(-33-80)^2+(-33-98)^2))/3
#cost함수 미분 -> w, b업데이트(bp)

#w=0.35, b=0
#hf(예상)=[27,33,33]    hf=xtrain*w+b

[array([-0.20715123], dtype=float32), array([-0.45067418], dtype=float32), array([-17.022772, -20.130041, -20.544344], dtype=float32)]


In [89]:
#우리의 모델
hf=xtrain*w+b
cost=tf.reduce_mean(tf.square(hf-ytrain))
#(예상값-실제값)합의제곱에 대한 평균

In [90]:
opt=tf.train.GradientDescentOptimizer(0.0001)
train=opt.minimize(cost)

In [91]:
for step in range(2001):
    sess.run(train)
    if step%100==0:
        print(step, sess.run(cost), 
              sess.run(w), sess.run(b))

0 5164.383 [1.785047] [-0.4288277]
100 9.475824 [0.9959845] [-0.4348249]
200 9.47512 [0.99595535] [-0.43218136]
300 9.47441 [0.99592656] [-0.4295379]
400 9.473711 [0.9958974] [-0.42689443]
500 9.47303 [0.9958687] [-0.42425096]
600 9.472331 [0.99583954] [-0.4216075]
700 9.4716215 [0.99581075] [-0.41896403]
800 9.47091 [0.99578154] [-0.41632068]
900 9.470212 [0.9957527] [-0.4136786]
1000 9.469517 [0.99572396] [-0.41103783]
1100 9.468841 [0.99569505] [-0.40839735]
1200 9.468145 [0.99566615] [-0.40575686]
1300 9.467443 [0.9956372] [-0.40311638]
1400 9.466739 [0.99560827] [-0.4004759]
1500 9.466023 [0.99557924] [-0.3978354]
1600 9.465331 [0.9955502] [-0.39519498]
1700 9.464647 [0.99552137] [-0.39255556]
1800 9.463941 [0.9954926] [-0.3899176]
1900 9.463246 [0.9954637] [-0.3872801]
2000 9.462556 [0.99543464] [-0.3846426]


In [97]:
#모의고사 점수가 50점=> 수능점수?
yhat=sess.run(w)[0]*50+sess.run(b)[0]
print(yhat)

49.3870894908905


In [98]:
#car 데이터에서
#임의의 실린더 수(10,12,16)가 입력 -> hp?
#cost, w, b 출력
#cost 함수 시각화(w축)
#learning rate, training 조절